#Ansible build file
---
- hosts: kali
  remote_user: ec2-user
  become: yes
  gather_facts: no

  tasks:
  - name: update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: get ssm agent
    get_url: 
      url: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
      dest: amazon-ssm-agent.deb
      checksum: sha256:677925efab7eeec34854dfe092c33d7a11a4d44549ab42ca21d73b12b253efd6

  - name: install ssm agent
    shell: dpkg -i amazon-ssm-agent.deb

  - name : start ssm agent
    shell: systemctl enable amazon-ssm-agent
